"""SOC 2 Trust Services Criteria, bring-your-own (#410).

**EVERY FIXTURE HERE IS SYNTHETIC.** No session holds real TSC text (the
user's decision on #410, and 80's rules). The criteria and the mapping below
are invented, written in the TSC's publicly known shape (`CC1.1`, points of
focus) with no AICPA wording, and generated by this file. NIST's Rev 4 to
Rev 5 comparison workbook is the one real input: a US government work,
pinned by hash in `tests/fixtures/`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from click.testing import CliRunner

from policyforge.ingest import nist_rev4_rev5, soc2_tsc

ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = ROOT / "tests" / "fixtures" / "sp800-53r4-to-r5-comparison-workbook.xlsx"

SYNTHETIC_CRITERIA = """SYNTHETIC TEST INPUT - NOT AICPA TEXT
An invented preamble line.
CC1.1 The synthetic entity keeps an invented register of widgets.
An invented point of focus.
Another invented point of focus.
CC1.2 The synthetic entity reviews the invented register.
CC2.1 An invented second group's first criterion.
A1.1 An invented availability-shaped criterion.
"""


def _synthetic_mapping(path: Path, rows) -> Path:
    import openpyxl

    book = openpyxl.Workbook()
    sheet = book.active
    sheet.title = "SYNTHETIC mapping"
    sheet.append(["SYNTHETIC - not the AICPA mapping"])
    sheet.append(["TSC Reference", "Invented text", "NIST SP 800-53 Controls"])
    for row in rows:
        sheet.append(list(row))
    book.save(path)
    return path


@pytest.fixture(scope="module")
def changed():
    return nist_rev4_rev5.parse(WORKBOOK.read_bytes())


@pytest.fixture(scope="module")
def rev5_ids():
    rows = json.loads(
        (ROOT / "data" / "frameworks" / "nist-800-53-r5" / "controls.json").read_text("utf-8")
    )
    return {r["control_id"] for r in rows} | {
        e["enhancement_id"] for r in rows for e in r["enhancements"]
    }


# ---- NIST's Rev 4 to Rev 5 workbook (real, public, pinned) -----------------------------


def test_the_workbook_is_its_pinned_extent(changed):
    assert (len(changed), sum(changed.values())) == nist_rev4_rev5.EXTENT == (1189, 698)


def test_a_parse_of_another_extent_is_refused(monkeypatch):
    monkeypatch.setattr(nist_rev4_rev5, "EXTENT", (1189, 697))
    with pytest.raises(nist_rev4_rev5.Rev4Rev5Error, match="Refusing"):
        nist_rev4_rev5.parse(WORKBOOK.read_bytes())


def test_a_different_workbook_is_refused():
    with pytest.raises(nist_rev4_rev5.Rev4Rev5Error, match="not the pinned"):
        nist_rev4_rev5.parse(b"not the workbook")


def test_every_id_the_rev5_catalog_lacks_is_labelled_withdrawn(changed, rev5_ids):
    """NIST's OSCAL Rev 5 marks all 182 such ids withdrawn (ba, measured on #410)."""
    labels = [nist_rev4_rev5.label(i, changed, rev5_ids) for i in changed if i not in rev5_ids]
    assert len(labels) == 182
    assert set(labels) == {nist_rev4_rev5.WITHDRAWN}


def test_labels_follow_nists_column(changed, rev5_ids):
    assert nist_rev4_rev5.label("AC-2", changed, rev5_ids) == nist_rev4_rev5.CHANGED
    assert changed["AC-3"] in (True, False)
    unchanged = next(i for i, flag in changed.items() if not flag and i in rev5_ids)
    assert nist_rev4_rev5.label(unchanged, changed, rev5_ids) is None
    assert nist_rev4_rev5.label("ZZ-9", changed, rev5_ids) is None, "the caller refuses it"


# ---- the criteria (synthetic) ----------------------------------------------------------------


def test_the_criteria_parse_with_points_of_focus():
    parsed = soc2_tsc.parse_criteria(SYNTHETIC_CRITERIA, version="synthetic")
    assert [c.control_id for c in parsed.controls] == ["CC1.1", "CC1.2", "CC2.1", "A1.1"]
    assert parsed.series == {"CC": 3, "A": 1}
    assert parsed.preamble_lines == 2
    first = parsed.controls[0]
    assert first.control_statement.startswith("The synthetic entity keeps")
    assert first.discussion.splitlines() == [
        "An invented point of focus.",
        "Another invented point of focus.",
    ]
    assert {c.framework for c in parsed.controls} == {soc2_tsc.FRAMEWORK}


@pytest.mark.parametrize(
    ("label", "change", "complaint"),
    [
        ("a gap in a group", ("CC1.2 ", "CC1.3 "), "without a gap"),
        ("a repeated id", ("A1.1 ", "CC1.1 "), "appears twice"),
        ("a line that starts like an id", ("CC2.1 An", "CC2. An"), "starts like a criterion id"),
        ("a dashed id", ("CC2.1 An", "CC2-1 An"), "starts like a criterion id"),
        ("a spaced id", ("CC2.1 An", "CC 2.1 An"), "starts like a criterion id"),
        (
            "an empty criterion",
            ("A1.1 An invented availability-shaped criterion.", "A1.1"),
            "no text",
        ),
    ],
)
def test_a_differently_shaped_file_is_refused_whole(label, change, complaint):
    """Shapes a real export could plausibly take, written from the domain,
    not from the parser's pattern: each would lose or misplace a criterion
    if the parser were lenient."""
    old, new = change
    assert SYNTHETIC_CRITERIA.count(old) == 1, label
    with pytest.raises(soc2_tsc.TscError, match=complaint):
        soc2_tsc.parse_criteria(SYNTHETIC_CRITERIA.replace(old, new), version="s")


def test_a_file_with_no_criteria_is_refused():
    with pytest.raises(soc2_tsc.TscError, match="No criterion ids"):
        soc2_tsc.parse_criteria("SYNTHETIC\njust prose\n", version="s")


# ---- the mapping (synthetic), resolved against Rev 5 -------------------------------------


def test_the_mapping_resolves_flags_and_refuses_by_name(tmp_path, changed, rev5_ids):
    path = _synthetic_mapping(
        tmp_path / "m.xlsx",
        [
            ("CC1.1", "x", "AC-02, AC-3(1)"),
            ("CC1.2", "x", "ZZ-9; IA-5\nnot-an-id"),
            ("CC2.1", "x", "AC-2"),
        ],
    )
    mapping = soc2_tsc.parse_mapping(
        path.read_bytes(),
        criteria={"CC1.1", "CC1.2", "CC2.1", "A1.1"},
        rev5_ids=rev5_ids,
        changed=changed,
    )
    assert mapping.links == {"CC1.1": ["AC-2"], "CC1.2": ["IA-5"], "CC2.1": ["AC-2"]}
    assert mapping.flagged == {"AC-2": nist_rev4_rev5.CHANGED, "IA-5": nist_rev4_rev5.CHANGED}
    assert mapping.refused == [
        ("CC1.1", "AC-3(1)", nist_rev4_rev5.WITHDRAWN),
        ("CC1.2", "ZZ-9", "not an id of SP 800-53 Rev 5"),
        ("CC1.2", "not-an-id", "not an 800-53 id"),
    ]


def test_a_mapping_naming_a_criterion_the_file_lacks_is_refused(tmp_path, changed, rev5_ids):
    path = _synthetic_mapping(tmp_path / "m.xlsx", [("CC9.9", "x", "AC-2")])
    with pytest.raises(soc2_tsc.TscError, match="does not have"):
        soc2_tsc.parse_mapping(
            path.read_bytes(), criteria={"CC1.1"}, rev5_ids=rev5_ids, changed=changed
        )


def test_a_mapping_without_both_headings_is_refused(tmp_path, changed, rev5_ids):
    import openpyxl

    book = openpyxl.Workbook()
    book.active.append(["SYNTHETIC", "no usable headings"])
    book.save(tmp_path / "m.xlsx")
    with pytest.raises(soc2_tsc.TscError, match="expected exactly one"):
        soc2_tsc.parse_mapping(
            (tmp_path / "m.xlsx").read_bytes(),
            criteria={"CC1.1"},
            rev5_ids=rev5_ids,
            changed=changed,
        )


# ---- the ETL, on the user's path, and the boundary --------------------------------------------


@pytest.fixture
def project(tmp_path, monkeypatch):
    import policyforge.cli as cli_mod

    monkeypatch.setattr(cli_mod, "load_config", lambda: {})
    monkeypatch.setattr("policyforge.frameworks.registry.is_ignored", lambda path: True)
    (tmp_path / "local_content").mkdir()
    (tmp_path / "local_content" / "criteria.txt").write_text(SYNTHETIC_CRITERIA, encoding="utf-8")
    _synthetic_mapping(
        tmp_path / "local_content" / "mapping.xlsx", [("CC1.1", "x", "AC-02, AC-3(1)")]
    )
    monkeypatch.chdir(tmp_path)
    return tmp_path


def _run(*args):
    from policyforge import cli as cli_mod

    return CliRunner().invoke(cli_mod.cli, ["etl-soc2-tsc", *args])


def test_the_etl_writes_a_licensed_catalog_and_its_manifest(project):
    import yaml

    out = project / "local_content" / "soc2-tsc" / "controls.json"
    result = _run(
        "--criteria",
        "local_content/criteria.txt",
        "--mapping",
        "local_content/mapping.xlsx",
        "--nist-comparison",
        str(WORKBOOK),
        "--out",
        str(out),
    )
    assert result.exit_code == 0, result.output
    rows = json.loads(out.read_text(encoding="utf-8"))
    assert [r["control_id"] for r in rows] == ["CC1.1", "CC1.2", "CC2.1", "A1.1"]
    assert rows[0]["source_crosswalk"] == {"nist-800-53": "AC-2"}
    manifest = yaml.safe_load((out.parent / "framework.yaml").read_text(encoding="utf-8"))
    assert manifest["licence"] == "licensed"
    assert manifest["framework_id"] == "aicpa-tsc"
    assert manifest["crosswalk_relationship"] == "source-untyped"
    assert manifest["crosswalk_source"] == soc2_tsc.CROSSWALK_SOURCE
    assert manifest["crosswalk_changed_since_rev4"] == {"AC-2": nist_rev4_rev5.CHANGED}
    assert manifest["crosswalk_refused"] == [
        {"criterion": "CC1.1", "target": "AC-3(1)", "reason": nist_rev4_rev5.WITHDRAWN}
    ]
    assert "not mapped by the source: CC1.2, CC2.1, A1.1" in result.output


def test_the_etl_refuses_a_destination_outside_the_boundary_and_writes_nothing(project):
    out = project / "output" / "tsc" / "controls.json"
    result = _run("--criteria", "local_content/criteria.txt", "--out", str(out), "--force")
    assert result.exit_code != 0
    assert "would be read as organization-internal" in result.output
    assert not out.exists()


def test_a_refused_parse_writes_nothing(project):
    (project / "local_content" / "criteria.txt").write_text(
        SYNTHETIC_CRITERIA.replace("CC1.2 ", "CC1.3 "), encoding="utf-8"
    )
    out = project / "local_content" / "soc2-tsc" / "controls.json"
    result = _run("--criteria", "local_content/criteria.txt", "--out", str(out))
    assert result.exit_code != 0
    assert "Nothing was written" in result.output
    assert not out.exists() and not (out.parent / "framework.yaml").exists()


def test_by_default_the_catalog_reaches_only_local_models(project):
    """The DEFAULT half of 80's amended rule (#410): with no boundary
    declaration, TSC content goes to local models only. The declared-widening
    half waits on 80's ruling on #459 about which declaration is real."""
    from policyforge.llm import boundary

    out = project / "local_content" / "soc2-tsc" / "controls.json"
    assert _run("--criteria", "local_content/criteria.txt", "--out", str(out)).exit_code == 0
    path = Path("local_content/soc2-tsc/controls.json")
    assert boundary.classify_path(path, {}).klass == boundary.LICENSED
    with pytest.raises(boundary.BoundaryViolation):
        boundary.enforce(path, {"llm": {"provider": "anthropic", "model": "any"}})
    local = {"llm": {"provider": "openai-compat", "base_url": "http://127.0.0.1:11434/v1"}}
    assert boundary.enforce(path, local).allowed


def test_coverage_reads_the_mapping_as_partial_and_names_its_source(project):
    """Through #408's declared-relationship and #449's source name, read from
    the user's own manifest: a TSC criterion is never counted fully covered on
    the AICPA's untyped link, and /coverage says whose mapping it is."""
    from policyforge.crosswalk.overlay import relationships_for
    from policyforge.frameworks.registry import (
        declared_crosswalk_relationships,
        declared_crosswalk_sources,
    )
    from policyforge.ingest.schema import load_controls

    out = project / "local_content" / "soc2-tsc" / "controls.json"
    assert (
        _run(
            "--criteria",
            "local_content/criteria.txt",
            "--mapping",
            "local_content/mapping.xlsx",
            "--nist-comparison",
            str(WORKBOOK),
            "--out",
            str(out),
        ).exit_code
        == 0
    )
    roots = [project / "local_content"]
    declared = declared_crosswalk_relationships(roots=roots)
    assert declared.get("aicpa-tsc") == "source-untyped"
    assert declared_crosswalk_sources(roots=roots).get("aicpa-tsc") == soc2_tsc.CROSSWALK_SOURCE
    controls = load_controls(out)
    table = relationships_for(controls, [], declared=declared)
    assert table == {("aicpa-tsc", "CC1.1", "AC-2"): "source-untyped"}
